name: Rebuild Manifest (weekly)

on:
  schedule:
    - cron: "10 3 * * 1"   # montags 03:10 UTC
  workflow_dispatch: {}
  push:
    paths:
      - "scripts/**"
      - ".github/workflows/rebuild-manifest.yml"
      - "requirements.txt"

permissions:
  contents: write

concurrency:
  group: rebuild-manifest
  cancel-in-progress: false

jobs:
  rebuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rebuild manifest
        run: |
          python scripts/rebuild_manifest.py

      - name: Commit & push if changed
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add manifest_latest.csv
          if git diff --staged --quiet; then
            echo "No changes – nothing to commit."
          else
            CHANGES=$(git diff --name-only --staged | tr '\n' ' ')
            git commit -m "ci: rebuild manifest_latest.csv (${CHANGES})"
            git push
          fi
